#ifndef __SYSTRACKER_BIT_FIELDS_H__
#define __SYSTRACKER_BIT_FIELDS_H__

#define PLT_TRACKER_VALID_S		24
#define PLT_TRACKER_VALID_E		24
#define PLT_TRACKER_SECURE_S		23
#define PLT_TRACKER_SECURE_E		23
#define PLT_TRACKER_ID_S		10
#define PLT_TRACKER_ID_E		22
#define PLT_TRACKER_DATA_SIZE_S		6
#define PLT_TRACKER_DATA_SIZE_E		8
#define PLT_TRACKER_BURST_LEN_S		2
#define PLT_TRACKER_BURST_LEN_E		5

#endif /* end of __SYSTRACKER_BIT_FIELDS_H__ */
