#ifndef __SYSTRACKER_BIT_FIELDS_H__
#define __SYSTRACKER_BIT_FIELDS_H__

#define PLT_TRACKER_VALID_S		26
#define PLT_TRACKER_VALID_E		26
#define PLT_TRACKER_SECURE_S		25
#define PLT_TRACKER_SECURE_E		25
#define PLT_TRACKER_ID_S		11
#define PLT_TRACKER_ID_E		24
#define PLT_TRACKER_DATA_SIZE_S		7
#define PLT_TRACKER_DATA_SIZE_E		9
#define PLT_TRACKER_BURST_LEN_S		3
#define PLT_TRACKER_BURST_LEN_E		6

#endif /* end of __SYSTRACKER_BIT_FIELDS_H__ */
